#!/usr/bin/env python3
"""
Bake the along-track water depth used by the "Staircase to the Sea" chart:
lib/data/vizBathymetry.ts

Samples public/geo/terrain.png (AWS Terrain Tiles / Terrarium: NOAA coastal
relief + ETOPO bathymetry for salt water; the Great Lakes carry no lake-floor
data in that source, so only tidal water returns depths) along the
water-following route in lib/data/routePath.ts, splits the track into voyage
days at the overnight waypoints in lib/data/waypoints.ts, and writes, per day,
[t (0..1 through the day), depth ft below sea level] pairs.

Run:  python3 scripts/geo/bake-profile.py      (needs pillow + numpy)
"""
import math, os, re
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LNG_MIN, LNG_MAX, LAT_MIN, LAT_MAX = -89.0, -71.0, 40.0, 47.5  # lib/geo/projection.ts BBOX
FT = 3.28084
STEP_NM = 0.25
LEGS = ("sound-saybrook",)  # the only leg the source carries depth for (Hudson is sub-pixel)

img = np.asarray(Image.open(os.path.join(ROOT, "public/geo/terrain.png")).convert("RGBA")).astype(np.float64)
H, W = img.shape[:2]
elev = (img[..., 0] * 256 + img[..., 1]) / 4 - 1000
water = img[..., 2]


def sample(lng, lat):
    """Bilinear elevation (m) + water mask at lng/lat."""
    fx = (lng - LNG_MIN) / (LNG_MAX - LNG_MIN) * W - 0.5
    fy = (LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * H - 0.5
    x0, y0 = int(math.floor(fx)), int(math.floor(fy))
    tx, ty = fx - x0, fy - y0
    def px(a, x, y):
        return a[min(max(y, 0), H - 1), min(max(x, 0), W - 1)]
    def bil(a):
        return (px(a, x0, y0) * (1 - tx) * (1 - ty) + px(a, x0 + 1, y0) * tx * (1 - ty)
                + px(a, x0, y0 + 1) * (1 - tx) * ty + px(a, x0 + 1, y0 + 1) * tx * ty)
    return bil(elev), bil(water)


def hav_nm(a, b):
    R = 3440.065
    la1, la2 = math.radians(a[1]), math.radians(b[1])
    dla, dln = la2 - la1, math.radians(b[0] - a[0])
    h = math.sin(dla / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin(dln / 2) ** 2
    return 2 * R * math.asin(math.sqrt(h))


# ── Parse route segments + waypoints straight from the TS sources ────────────
route_src = open(os.path.join(ROOT, "lib/data/routePath.ts")).read()
segments = {}
for m in re.finditer(r'leg:\s*"([a-z-]+)",\s*inland:\s*\w+,\s*coords:\s*\[(.*?)\n\s*\],', route_src, re.S):
    pts = [(float(a), float(b)) for a, b in re.findall(r'\[\s*(-?[\d.]+),\s*(-?[\d.]+)\s*\]', m.group(2))]
    segments[m.group(1)] = pts

wp_src = open(os.path.join(ROOT, "lib/data/waypoints.ts")).read()
waypoints = [(float(lat), float(lng), int(day), leg) for lat, lng, day, leg in re.findall(
    r'lat:\s*(-?[\d.]+),\s*lng:\s*(-?[\d.]+),\s*day:\s*(\d+),\s*leg:\s*"([a-z-]+)"', wp_src)]
by_day = {d: (lng, lat) for lat, lng, d, _ in waypoints}

out = {}
for leg in LEGS:
    pts = segments[leg]
    # Densify the polyline.
    dense = [pts[0]]
    for a, b in zip(pts, pts[1:]):
        n = max(1, int(math.ceil(hav_nm(a, b) / STEP_NM)))
        for i in range(1, n + 1):
            dense.append((a[0] + (b[0] - a[0]) * i / n, a[1] + (b[1] - a[1]) * i / n))
    cum = [0.0]
    for a, b in zip(dense, dense[1:]):
        cum.append(cum[-1] + hav_nm(a, b))
    # Days on this leg, with the index of the densified vertex nearest each overnight.
    days = sorted(d for _, _, d, lg in waypoints if lg == leg)
    prev_day_of = {d: max([x for x in by_day if x < d], default=None) for d in days}
    def nearest(lnglat):
        return int(np.argmin([hav_nm(lnglat, p) for p in dense]))
    for d in days:
        p = prev_day_of[d]
        if p is None or by_day[p] == by_day[d]:
            continue  # layover day / no movement
        i0 = nearest(by_day[p]) if by_day[p] else 0
        i1 = nearest(by_day[d])
        if i1 <= i0:
            continue
        span = cum[i1] - cum[i0]
        rows = []
        for i in range(i0, i1 + 1):
            e, w = sample(*dense[i])
            depth = round(-e * FT) if (w > 128 and e < 0) else None
            rows.append((round((cum[i] - cum[i0]) / span, 4), depth))
        # light 3-tap median to kill single-pixel speckle
        vals = [r[1] for r in rows]
        sm = []
        for i in range(len(vals)):
            win = [v for v in vals[max(0, i - 1):i + 2] if v is not None]
            sm.append(int(np.median(win)) if vals[i] is not None and win else None)
        # thin to ~1 sample / 0.5 nm
        keep = [(t, v) for k, ((t, _), v) in enumerate(zip(rows, sm)) if k % 2 == 0 or k == len(rows) - 1]
        out[d] = keep

lines = [
    "// AUTO-GENERATED by scripts/geo/bake-profile.py — do not edit by hand.",
    "// Along-track water depth (ft below sea level) sampled from public/geo/terrain.png",
    "// (AWS Terrain Tiles: NOAA coastal relief / ETOPO bathymetry) on the routePath.ts",
    "// track, split at each overnight waypoint. t = 0..1 through the day's run;",
    "// null = no depth data (narrow river / land-masked pixel). Only tidal legs carry",
    "// bathymetry in the source — the Great Lakes surfaces are flat in it.",
    "",
    "export const TRACK_DEPTH_FT: Record<number, [number, number | null][]> = {",
]
for d in sorted(out):
    body = ", ".join(f"[{t}, {'null' if v is None else v}]" for t, v in out[d])
    lines.append(f"  {d}: [{body}],")
lines.append("};")
lines.append("")
dst = os.path.join(ROOT, "lib/data/vizBathymetry.ts")
open(dst, "w").write("\n".join(lines))
for d in sorted(out):
    vs = [v for _, v in out[d] if v is not None]
    print(f"day {d}: {len(out[d])} samples, max depth {max(vs) if vs else None} ft")
print("wrote", dst)
